package pos.stalupita.model;
// Generated 12/06/2018 11:57:14 AM by Hibernate Tools 4.3.1



/**
 * Configuracion generated by hbm2java
 */
public class Configuracion  implements java.io.Serializable {


     private int idconfig;
     private String descripcion;
     private String valor;

    public Configuracion() {
    }

    public Configuracion(int idconfig, String descripcion, String valor) {
       this.idconfig = idconfig;
       this.descripcion = descripcion;
       this.valor = valor;
    }
   
    public int getIdconfig() {
        return this.idconfig;
    }
    
    public void setIdconfig(int idconfig) {
        this.idconfig = idconfig;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getValor() {
        return this.valor;
    }
    
    public void setValor(String valor) {
        this.valor = valor;
    }




}


