package pos.stalupita.model;
// Generated 12/06/2018 11:57:14 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Objects;

/**
 * DetalleTicket generated by hbm2java
 */
public class DetalleTicket implements java.io.Serializable {

    private Integer iddetticket;
    private Producto producto;
    private Ticket ticket;
    private BigDecimal precio;
    private BigDecimal cantidad;
    private BigDecimal total;
    private BigDecimal ganancia;

    public DetalleTicket() {
    }

    public DetalleTicket(Producto producto, Ticket ticket) {
        this.producto = producto;
        this.ticket = ticket;
    }

    public DetalleTicket(Integer iddetticket, Producto producto, Ticket ticket, BigDecimal precio, BigDecimal cantidad, BigDecimal total, BigDecimal ganancia) {
        this.iddetticket = iddetticket;
        this.producto = producto;
        this.ticket = ticket;
        this.precio = precio;
        this.cantidad = cantidad;
        this.total = total;
        this.ganancia = ganancia;
    }

    public Integer getIddetticket() {
        return this.iddetticket;
    }

    public void setIddetticket(Integer iddetticket) {
        this.iddetticket = iddetticket;
    }

    public Producto getProducto() {
        return this.producto;
    }

    public void setProducto(Producto producto) {
        this.producto = producto;
    }

    public Ticket getTicket() {
        return this.ticket;
    }

    public void setTicket(Ticket ticket) {
        this.ticket = ticket;
    }

    public BigDecimal getPrecio() {
        return this.precio;
    }

    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }

    public BigDecimal getCantidad() {
        return this.cantidad;
    }

    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }

    public BigDecimal getTotal() {
        return this.total;
    }

    public void setTotal(BigDecimal total) {
        this.total = total;
    }

    public BigDecimal getGanancia() {
        return ganancia;
    }

    public void setGanancia(BigDecimal ganancia) {
        this.ganancia = ganancia;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final DetalleTicket other = (DetalleTicket) obj;
        return this.producto.getIdproducto()== other.producto.getIdproducto()
                && this.ticket.getIdticket()== other.ticket.getIdticket()
                && this.precio.compareTo(other.precio) == 0;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 97 * hash + Objects.hashCode(this.producto);
        hash = 97 * hash + Objects.hashCode(this.ticket);
        hash = 97 * hash + Objects.hashCode(this.precio);
        return hash;
    }
}
