package pos.stalupita.model;
// Generated 11/06/2018 11:59:53 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * DetalleTicket generated by hbm2java
 */
public class DetalleTicket  implements java.io.Serializable {


     private Integer iddetticket;
     private Producto producto;
     private Ticket ticket;
     private BigDecimal precio;
     private BigDecimal cantidad;
     private BigDecimal total;

    public DetalleTicket() {
    }

	
    public DetalleTicket(Producto producto, Ticket ticket) {
        this.producto = producto;
        this.ticket = ticket;
    }
    public DetalleTicket(Producto producto, Ticket ticket, BigDecimal precio, BigDecimal cantidad, BigDecimal total) {
       this.producto = producto;
       this.ticket = ticket;
       this.precio = precio;
       this.cantidad = cantidad;
       this.total = total;
    }
   
    public Integer getIddetticket() {
        return this.iddetticket;
    }
    
    public void setIddetticket(Integer iddetticket) {
        this.iddetticket = iddetticket;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Ticket getTicket() {
        return this.ticket;
    }
    
    public void setTicket(Ticket ticket) {
        this.ticket = ticket;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }
    public BigDecimal getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }
    public BigDecimal getTotal() {
        return this.total;
    }
    
    public void setTotal(BigDecimal total) {
        this.total = total;
    }




}


