package pos.stalupita.model;
// Generated 11/06/2018 11:59:53 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Inventario generated by hbm2java
 */
public class Inventario  implements java.io.Serializable {


     private Integer idinventario;
     private Producto producto;
     private BigDecimal cantidadComprada;
     private BigDecimal precio;
     private BigDecimal total;
     private BigDecimal cantidadVendida;
     private Date fechaCompra;
     private Date fechaVendido;
     private Boolean estado;

    public Inventario() {
    }

	
    public Inventario(Producto producto) {
        this.producto = producto;
    }
    public Inventario(Producto producto, BigDecimal cantidadComprada, BigDecimal precio, BigDecimal total, BigDecimal cantidadVendida, Date fechaCompra, Date fechaVendido, Boolean estado) {
       this.producto = producto;
       this.cantidadComprada = cantidadComprada;
       this.precio = precio;
       this.total = total;
       this.cantidadVendida = cantidadVendida;
       this.fechaCompra = fechaCompra;
       this.fechaVendido = fechaVendido;
       this.estado = estado;
    }
   
    public Integer getIdinventario() {
        return this.idinventario;
    }
    
    public void setIdinventario(Integer idinventario) {
        this.idinventario = idinventario;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public BigDecimal getCantidadComprada() {
        return this.cantidadComprada;
    }
    
    public void setCantidadComprada(BigDecimal cantidadComprada) {
        this.cantidadComprada = cantidadComprada;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }
    public BigDecimal getTotal() {
        return this.total;
    }
    
    public void setTotal(BigDecimal total) {
        this.total = total;
    }
    public BigDecimal getCantidadVendida() {
        return this.cantidadVendida;
    }
    
    public void setCantidadVendida(BigDecimal cantidadVendida) {
        this.cantidadVendida = cantidadVendida;
    }
    public Date getFechaCompra() {
        return this.fechaCompra;
    }
    
    public void setFechaCompra(Date fechaCompra) {
        this.fechaCompra = fechaCompra;
    }
    public Date getFechaVendido() {
        return this.fechaVendido;
    }
    
    public void setFechaVendido(Date fechaVendido) {
        this.fechaVendido = fechaVendido;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }




}


