package pos.stalupita.model;
// Generated 12/06/2018 11:57:14 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private Integer idproducto;
     private Categoria categoria;
     private UnidadMedida unidadMedida;
     private String descripcion;
     private BigDecimal costo;
     private BigDecimal precio;
     private Boolean estado;
     private Date createdAt;
     private Date updatedAt;
     private Date deletedAt;
     private Set inventarios = new HashSet(0);
     private Set detalleTickets = new HashSet(0);

    public Producto() {
    }

	
    public Producto(Categoria categoria, UnidadMedida unidadMedida) {
        this.categoria = categoria;
        this.unidadMedida = unidadMedida;
    }
    public Producto(Categoria categoria, UnidadMedida unidadMedida, String descripcion, BigDecimal costo, BigDecimal precio, Boolean estado, Date createdAt, Date updatedAt, Date deletedAt, Set inventarios, Set detalleTickets) {
       this.categoria = categoria;
       this.unidadMedida = unidadMedida;
       this.descripcion = descripcion;
       this.costo = costo;
       this.precio = precio;
       this.estado = estado;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.deletedAt = deletedAt;
       this.inventarios = inventarios;
       this.detalleTickets = detalleTickets;
    }
   
    public Integer getIdproducto() {
        return this.idproducto;
    }
    
    public void setIdproducto(Integer idproducto) {
        this.idproducto = idproducto;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public UnidadMedida getUnidadMedida() {
        return this.unidadMedida;
    }
    
    public void setUnidadMedida(UnidadMedida unidadMedida) {
        this.unidadMedida = unidadMedida;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public BigDecimal getCosto() {
        return this.costo;
    }
    
    public void setCosto(BigDecimal costo) {
        this.costo = costo;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public Date getDeletedAt() {
        return this.deletedAt;
    }
    
    public void setDeletedAt(Date deletedAt) {
        this.deletedAt = deletedAt;
    }
    public Set getInventarios() {
        return this.inventarios;
    }
    
    public void setInventarios(Set inventarios) {
        this.inventarios = inventarios;
    }
    public Set getDetalleTickets() {
        return this.detalleTickets;
    }
    
    public void setDetalleTickets(Set detalleTickets) {
        this.detalleTickets = detalleTickets;
    }




}


