package pos.stalupita.model;
// Generated 11/06/2018 11:59:53 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * UnidadMedida generated by hbm2java
 */
public class UnidadMedida  implements java.io.Serializable {


     private String idume;
     private String descripcion;
     private BigDecimal cantidad;
     private Boolean estado;
     private Set productos = new HashSet(0);

    public UnidadMedida() {
    }

	
    public UnidadMedida(String idume) {
        this.idume = idume;
    }
    public UnidadMedida(String idume, String descripcion, BigDecimal cantidad, Boolean estado, Set productos) {
       this.idume = idume;
       this.descripcion = descripcion;
       this.cantidad = cantidad;
       this.estado = estado;
       this.productos = productos;
    }
   
    public String getIdume() {
        return this.idume;
    }
    
    public void setIdume(String idume) {
        this.idume = idume;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public BigDecimal getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }




}


