/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pos.stalupita.view;

import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.annotation.Resource;
import javax.swing.AbstractAction;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.RowFilter;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import pos.stalupita.controller.ProductoController;
import pos.stalupita.herramientas.RoundedBorderBtn;
import pos.stalupita.herramientas.Utilities;
import pos.stalupita.model.Producto;
import pos.stalupita.tablemodels.TableModelCatProductos;

/**
 *
 * @author adrian.ake
 */
@Component
public class DlgAdminProductos extends javax.swing.JDialog {

    @Resource
    private ProductoController productoController;
    @Resource
    private DlgRegistrar_prod jdlgRegistrar_prod;

    /**
     * Creates new form DlgAdminProductos
     */
    public DlgAdminProductos(java.awt.Frame parent, boolean modal) {
        super(null, ModalityType.APPLICATION_MODAL);
        initComponents();
        Utilities.setDialogIcon(this);
        this.setMnemonic();
        this.cargarComponents();
    }

    @Autowired
    public DlgAdminProductos() {
        super(null, ModalityType.APPLICATION_MODAL);
        initComponents();
        Utilities.setDialogIcon(this);
        this.setMnemonic();
        this.cargarComponents();
    }

    private void cargarComponents() {
        this.btnNuevoProducto.setBorder(new RoundedBorderBtn(8));
        this.btnEditarProducto.setBorder(new RoundedBorderBtn(8));
        this.btnEliminarProducto.setBorder(new RoundedBorderBtn(8));
    }

    public final void setMnemonic() {
        getActionMap(btnNuevoProducto, "nuevo", KeyEvent.VK_N);
        getActionMap(btnEditarProducto, "editar", KeyEvent.VK_M);
        getActionMap(btnEliminarProducto, "eliminar", KeyEvent.VK_E);
        getActionMap(btnEliminarProducto, "cerrar", KeyEvent.VK_ESCAPE);

        btnNuevoProducto.setMnemonic(KeyEvent.VK_N);
        btnEditarProducto.setMnemonic(KeyEvent.VK_M);
        btnEliminarProducto.setMnemonic(KeyEvent.VK_E);
        btnCerrar.setMnemonic(KeyEvent.VK_ESCAPE);
    }

    public void getActionMap(JComponent componente, String nombreAccion, int tecla) {
        componente.getInputMap(JButton.WHEN_IN_FOCUSED_WINDOW).put(
                KeyStroke.getKeyStroke(tecla, 0), nombreAccion);
        componente.getActionMap().put(nombreAccion,
                newAbstractAction(nombreAccion));
    }

    public AbstractAction newAbstractAction(String nombreAccion) {
        if (nombreAccion.equals("nuevo")) {
            return new AbstractAction(nombreAccion) {
                @Override
                public void actionPerformed(ActionEvent evt) {
                    if (btnNuevoProducto.isEnabled()) {
                        btnNuevoProductoActionPerformed(evt);
                    }
                }
            };
        } else if (nombreAccion.equals("editar")) {
            return new AbstractAction(nombreAccion) {
                @Override
                public void actionPerformed(ActionEvent evt) {
                    if (btnEditarProducto.isEnabled()) {
                        btnEditarProductoActionPerformed(evt);
                    }
                }
            };
        } else if (nombreAccion.equals("eliminar")) {
            return new AbstractAction(nombreAccion) {
                @Override
                public void actionPerformed(ActionEvent evt) {
                    if (btnEliminarProducto.isEnabled()) {
                        btnEliminarProductoActionPerformed(evt);
                    }
                }
            };
        } else if (nombreAccion.equals("cerrar")) {
            return new AbstractAction(nombreAccion) {
                @Override
                public void actionPerformed(ActionEvent evt) {
                    if (btnCerrar.isEnabled()) {
                        btnCerrarActionPerformed(evt);
                    }
                }
            };
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tableModelCatProductos1 = new pos.stalupita.tablemodels.TableModelCatProductos();
        jpnlFondoGris = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnEditarProducto = new javax.swing.JButton();
        btnNuevoProducto = new javax.swing.JButton();
        btnEliminarProducto = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbCatlProductos = new javax.swing.JTable();
        jpnlFondoVerde = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jchckVerEliminados = new javax.swing.JCheckBox();
        jtxtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtTotalRegistros = new javax.swing.JTextField();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jpnlFondoGris.setBackground(new java.awt.Color(119, 136, 152));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(4, 151, 135), 2), "Opciones", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12), new java.awt.Color(0, 51, 153))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        btnEditarProducto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEditarProducto.setForeground(new java.awt.Color(51, 102, 255));
        btnEditarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/stalupita/view/resources/09_pencil-48.png"))); // NOI18N
        btnEditarProducto.setText("<html><center><b>Modificar</b> &nbsp<font color = blue>(Alt + M)</font> </center></html>");
        btnEditarProducto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditarProducto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarProductoActionPerformed(evt);
            }
        });

        btnNuevoProducto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNuevoProducto.setForeground(new java.awt.Color(51, 102, 255));
        btnNuevoProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/stalupita/view/resources/07_plus-48.png"))); // NOI18N
        btnNuevoProducto.setText("<html><center><b>Registrar</b> &nbsp<font color = blue>(Alt + N)</font> </center></html>");
        btnNuevoProducto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevoProducto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNuevoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoProductoActionPerformed(evt);
            }
        });

        btnEliminarProducto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEliminarProducto.setForeground(new java.awt.Color(51, 102, 255));
        btnEliminarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/stalupita/view/resources/010_trash-2-48.png"))); // NOI18N
        btnEliminarProducto.setText("<html><center><b>Eliminar</b> &nbsp<font color = blue>(Alt + E)</font> </center></html>");
        btnEliminarProducto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminarProducto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProductoActionPerformed(evt);
            }
        });

        btnCerrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(51, 102, 255));
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/stalupita/view/resources/07_minus-48.png"))); // NOI18N
        btnCerrar.setText("<html><center><b>Cerrar</b> &nbsp<font color = blue>(ESC)</font> </center></html>");
        btnCerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCerrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEditarProducto)
                    .addComponent(btnNuevoProducto)
                    .addComponent(btnEliminarProducto)
                    .addComponent(btnCerrar))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNuevoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEditarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEliminarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setBackground(new java.awt.Color(4, 151, 135));
        jScrollPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(4, 151, 135), 5, true));

        jtbCatlProductos.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jtbCatlProductos.setModel(tableModelCatProductos1);
        jScrollPane1.setViewportView(jtbCatlProductos);

        jpnlFondoVerde.setBackground(new java.awt.Color(4, 151, 135));
        jpnlFondoVerde.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Productos Registrados");

        javax.swing.GroupLayout jpnlFondoVerdeLayout = new javax.swing.GroupLayout(jpnlFondoVerde);
        jpnlFondoVerde.setLayout(jpnlFondoVerdeLayout);
        jpnlFondoVerdeLayout.setHorizontalGroup(
            jpnlFondoVerdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlFondoVerdeLayout.createSequentialGroup()
                .addGap(394, 394, 394)
                .addComponent(jLabel1)
                .addContainerGap(401, Short.MAX_VALUE))
        );
        jpnlFondoVerdeLayout.setVerticalGroup(
            jpnlFondoVerdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlFondoVerdeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jchckVerEliminados.setBackground(new java.awt.Color(119, 136, 152));
        jchckVerEliminados.setForeground(new java.awt.Color(255, 255, 255));
        jchckVerEliminados.setText("Mostrar Eliminados");
        jchckVerEliminados.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jchckVerEliminadosStateChanged(evt);
            }
        });

        jtxtNombre.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jtxtNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtNombreFocusGained(evt);
            }
        });
        jtxtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtNombreKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Total registros:");

        jtxtTotalRegistros.setEditable(false);
        jtxtTotalRegistros.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jtxtTotalRegistros.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtTotalRegistros.setText("0");

        javax.swing.GroupLayout jpnlFondoGrisLayout = new javax.swing.GroupLayout(jpnlFondoGris);
        jpnlFondoGris.setLayout(jpnlFondoGrisLayout);
        jpnlFondoGrisLayout.setHorizontalGroup(
            jpnlFondoGrisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlFondoGrisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnlFondoGrisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnlFondoGrisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jpnlFondoGrisLayout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jtxtTotalRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(123, 123, 123)
                            .addComponent(jchckVerEliminados))
                        .addGroup(jpnlFondoGrisLayout.createSequentialGroup()
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jpnlFondoGrisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jpnlFondoGrisLayout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jtxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 826, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jpnlFondoVerde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );
        jpnlFondoGrisLayout.setVerticalGroup(
            jpnlFondoGrisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlFondoGrisLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jpnlFondoVerde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jpnlFondoGrisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jpnlFondoGrisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnlFondoGrisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jchckVerEliminados)
                    .addGroup(jpnlFondoGrisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtxtTotalRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(jpnlFondoGris, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void btnNuevoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoProductoActionPerformed
        this.jdlgRegistrar_prod.setModal(true);
        this.jdlgRegistrar_prod.setLocationRelativeTo(this);
        this.jdlgRegistrar_prod.setTitulo("Registrar Producto");
        this.jdlgRegistrar_prod.resetDatos();
        this.jdlgRegistrar_prod.setVisible(true);
        this.cargarProductosActivos();
    }//GEN-LAST:event_btnNuevoProductoActionPerformed

    private void btnEditarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarProductoActionPerformed
        if (this.validacionXSeleccion()) {
            this.editarProducto();
            this.cargarProductosActivos();
        } else {
            JOptionPane.showMessageDialog(this, "Elige el producto que deseas editar", "Mensaje del Sistema", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnEditarProductoActionPerformed

    private void btnEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProductoActionPerformed
        if (this.validacionXSeleccion()) {
            this.eliminarProducto();
            this.cargarProductosActivos();
        } else {
            JOptionPane.showMessageDialog(this, "Elige el producto que deseas Eliminar", "Mensaje del Sistema", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarProductoActionPerformed

    private void jchckVerEliminadosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jchckVerEliminadosStateChanged
        if (this.jchckVerEliminados.isSelected()) {
            this.cargarTodosProductos();
        } else {
            this.cargarProductosActivos();
        }
    }//GEN-LAST:event_jchckVerEliminadosStateChanged

    private void jtxtNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtNombreFocusGained
        this.jtxtNombre.selectAll();
    }//GEN-LAST:event_jtxtNombreFocusGained

    private void jtxtNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtNombreKeyReleased
        if (!this.jtxtNombre.getText().isEmpty()) {
            try {
                TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(((TableModelCatProductos) this.jtbCatlProductos.getModel()));
                sorter.setRowFilter(RowFilter.regexFilter("(?i)" + this.jtxtNombre.getText()));

                this.jtbCatlProductos.setRowSorter(sorter);
            } catch (java.util.regex.PatternSyntaxException e) {
                return;
            }
        } else {
            this.jtbCatlProductos.setRowSorter(null);
        }
    }//GEN-LAST:event_jtxtNombreKeyReleased

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
        this.setVisible(false);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void cargarTodosProductos() {
        this.tableModelCatProductos1 = new TableModelCatProductos();
        this.jtbCatlProductos.setModel(tableModelCatProductos1);

        this.tableModelCatProductos1.change(new ArrayList<Producto>());
        List<Producto> productos = this.productoController.getAllProductos();
        this.tableModelCatProductos1.change(productos);

        TableColumn columna_0 = this.jtbCatlProductos.getColumnModel().getColumn(0);//col id
        columna_0.setMaxWidth(30);

        this.jtxtTotalRegistros.setText(String.valueOf(this.jtbCatlProductos.getRowCount()));
    }

    private void cargarProductosActivos() {
        this.tableModelCatProductos1 = new TableModelCatProductos();
        this.jtbCatlProductos.setModel(this.tableModelCatProductos1);

        this.tableModelCatProductos1.change(new ArrayList<Producto>());
        List<Producto> productos = this.productoController.getAllProductosActivos();
        this.tableModelCatProductos1.change(productos);

        TableColumn columna_0 = this.jtbCatlProductos.getColumnModel().getColumn(0);//col id
        columna_0.setMaxWidth(30);

        TableColumn columna_8 = this.jtbCatlProductos.getColumnModel().getColumn(8);
        this.jtbCatlProductos.getColumnModel().removeColumn(columna_8);

        this.jtxtTotalRegistros.setText(String.valueOf(this.jtbCatlProductos.getRowCount()));
    }

    @Override
    public void setVisible(boolean b) {
        this.cargarProductosActivos();
        this.jtbCatlProductos.getTableHeader().setFont(new Font("SansSerif", Font.BOLD, 13));
        super.setVisible(b); //To change body of generated methods, choose Tools | Templates.
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEditarProducto;
    private javax.swing.JButton btnEliminarProducto;
    private javax.swing.JButton btnNuevoProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox jchckVerEliminados;
    private javax.swing.JPanel jpnlFondoGris;
    private javax.swing.JPanel jpnlFondoVerde;
    private javax.swing.JTable jtbCatlProductos;
    private javax.swing.JTextField jtxtNombre;
    private javax.swing.JTextField jtxtTotalRegistros;
    private pos.stalupita.tablemodels.TableModelCatProductos tableModelCatProductos1;
    // End of variables declaration//GEN-END:variables

    private void editarProducto() {
        Integer index_selected = this.jtbCatlProductos.getSelectedRow();
        Producto producto_edit = this.getProductoXIndex(index_selected);
        if (producto_edit.getEstado()) {
            this.jdlgRegistrar_prod.setModal(true);
            this.jdlgRegistrar_prod.setLocationRelativeTo(this);
            this.jdlgRegistrar_prod.setTitulo("Editar Producto");
            this.jdlgRegistrar_prod.resetDatos();
            this.jdlgRegistrar_prod.setEditProducto(producto_edit);
            this.jdlgRegistrar_prod.setProducto_edition(producto_edit);
            this.jdlgRegistrar_prod.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Los productos eliminados no pueden ser editados", "Mensaje del Sistema", JOptionPane.WARNING_MESSAGE);
        }
    }

    private boolean validacionXSeleccion() {
        Integer index_selected = this.jtbCatlProductos.getSelectedRow();
        return index_selected != -1;
    }

    public Producto getProductoXIndex(Integer index) {
        return this.tableModelCatProductos1.get(index);
    }

    private void eliminarProducto() {
        Integer index_selected = this.jtbCatlProductos.getSelectedRow();
        Producto producto_del = this.getProductoXIndex(index_selected);
        String msg_html = "<html><center>"
                + " ¿Está seguro que desea Eliminar el producto"
                + "<b>" + producto_del.getDescripcion() + "</b>? "
                + "</center></html>";
        JLabel jLabel = new JLabel(msg_html);       
        
        if (JOptionPane.showConfirmDialog(null, jLabel, "Mensaje del Sistema", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE) == JOptionPane.YES_OPTION) {
            producto_del.setDeletedAt(new Date());
            producto_del.setEstado(false);
            this.productoController.guardarUpdProducto(producto_del);
            JOptionPane.showMessageDialog(this, "El producto ha sido eliminado", "Mensaje del Sistema", JOptionPane.INFORMATION_MESSAGE);
        }
    }

}
