/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pos.stalupita.view;

import java.util.ArrayList;
import java.util.List;
import javax.annotation.Resource;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;
import pos.stalupita.controller.TicketController;
import pos.stalupita.herramientas.Utilities;
import pos.stalupita.model.DetalleTicket;
import pos.stalupita.model.Ticket;

/**
 *
 * @author adrian.ake
 */
@Scope(value = "prototype")
@Component
public class DlgDetallesTicket extends javax.swing.JDialog {

    private static org.apache.log4j.Logger log = org.apache.log4j.Logger.getLogger(DlgDetallesTicket.class.getName());
    @Resource
    private TicketController ticketController;

    private Ticket ticket_to_view;

    @Autowired
    public DlgDetallesTicket() {
        super(null, ModalityType.APPLICATION_MODAL);
        initComponents();
        Utilities.setDialogIcon(this);
        this.setResizable(false);
        this.getContentPane().setBackground(new java.awt.Color(149, 163, 190));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tableModelDetallesTicket1 = new pos.stalupita.tablemodels.TableModelDetallesTicket();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbDetallesTicket = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setTitle("Visualizar Detalles de Ventas");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(4, 151, 135));
        jScrollPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(4, 151, 135), 5, true));

        jtbDetallesTicket.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtbDetallesTicket.setModel(tableModelDetallesTicket1);
        jScrollPane1.setViewportView(jtbDetallesTicket);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Detalles de la venta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jLabel1)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    private void cargarDetallesXTicket() {
        try {
            this.tableModelDetallesTicket1.change(new ArrayList<DetalleTicket>());
            List<DetalleTicket> lista_detalles = this.ticketController.getDetfFromTckt(this.getTicket_to_view().getIdticket());
            this.tableModelDetallesTicket1.change(lista_detalles);
        } catch (Exception e) {
            log.error("Error al tratar de mostrar los detalles por ticket ", e);
        }
    }

    @Override
    public void setVisible(boolean b) {
        this.cargarDetallesXTicket();
        super.setVisible(b); //To change body of generated methods, choose Tools | Templates.
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbDetallesTicket;
    private pos.stalupita.tablemodels.TableModelDetallesTicket tableModelDetallesTicket1;
    // End of variables declaration//GEN-END:variables

    public Ticket getTicket_to_view() {
        return ticket_to_view;
    }

    public void setTicket_to_view(Ticket ticket_to_view) {
        this.ticket_to_view = ticket_to_view;
    }

}
