/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pos.stalupita.view;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.math.RoundingMode;
import javax.annotation.Resource;
import javax.swing.AbstractAction;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import pos.stalupita.controller.TicketController;
import pos.stalupita.herramientas.AdapterNumericoFormatMak;
import pos.stalupita.herramientas.Utilities;
import pos.stalupita.model.Ticket;

/**
 *
 * @author adrian.ake
 */
@Component
public class DlgPago extends javax.swing.JDialog {

    private static org.apache.log4j.Logger log = org.apache.log4j.Logger.getLogger(DlgPago.class.getName());

    @Resource
    private TicketController ticketController;

    private Ticket ticket_pagar = null;

    @Autowired
    public DlgPago(TicketController ticketController) {
        super(null, ModalityType.APPLICATION_MODAL);
        initComponents();
        Utilities.setDialogIcon(this);
        this.setMnemonic();
        this.jtxtPago.addKeyListener(new AdapterNumericoFormatMak(this.jtxtPago, 8, 2));
        this.ticketController = ticketController;
        this.setResizable(false);
        this.getContentPane().setBackground(new java.awt.Color(149, 163, 190));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCancelarVenta = new javax.swing.JButton();
        btnPagarVenta = new javax.swing.JButton();
        jtxtCambio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtTotalVenta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxtPago = new javax.swing.JTextField();
        jpnlFondoVerde = new javax.swing.JPanel();
        jblTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("pagar Venta");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        btnCancelarVenta.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnCancelarVenta.setForeground(new java.awt.Color(51, 102, 255));
        btnCancelarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/stalupita/view/resources/010_x-24.png"))); // NOI18N
        btnCancelarVenta.setText("<html><center><b>Cancelar</b><br><font color = blue>(ESC)</font> </center></html>");
        btnCancelarVenta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelarVenta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancelarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarVentaActionPerformed(evt);
            }
        });

        btnPagarVenta.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnPagarVenta.setForeground(new java.awt.Color(51, 102, 255));
        btnPagarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/stalupita/view/resources/011_yes-24.png"))); // NOI18N
        btnPagarVenta.setText("<html><center><b>Aceptar</b> &nbsp<br><font color = blue>(Alt+Enter)</font> </center></html>");
        btnPagarVenta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPagarVenta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPagarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarVentaActionPerformed(evt);
            }
        });

        jtxtCambio.setEditable(false);
        jtxtCambio.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jtxtCambio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtCambio.setText("0");
        jtxtCambio.setFocusable(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setLabelFor(jtxtCambio);
        jLabel3.setText("Cambio $:");

        jtxtTotalVenta.setEditable(false);
        jtxtTotalVenta.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jtxtTotalVenta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtTotalVenta.setText("0.00");
        jtxtTotalVenta.setFocusable(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setLabelFor(jtxtTotalVenta);
        jLabel2.setText("Total $:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setLabelFor(jtxtPago);
        jLabel4.setText("Pago $:");

        jtxtPago.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jtxtPago.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtPago.setText("0.00");
        jtxtPago.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtPagoFocusGained(evt);
            }
        });
        jtxtPago.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtPagoKeyReleased(evt);
            }
        });

        jpnlFondoVerde.setBackground(new java.awt.Color(4, 151, 135));
        jpnlFondoVerde.setBorder(new javax.swing.border.SoftBevelBorder(0));

        jblTitulo.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jblTitulo.setText("Pagar Venta");

        javax.swing.GroupLayout jpnlFondoVerdeLayout = new javax.swing.GroupLayout(jpnlFondoVerde);
        jpnlFondoVerde.setLayout(jpnlFondoVerdeLayout);
        jpnlFondoVerdeLayout.setHorizontalGroup(
            jpnlFondoVerdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlFondoVerdeLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jblTitulo)
                .addContainerGap(121, Short.MAX_VALUE))
        );
        jpnlFondoVerdeLayout.setVerticalGroup(
            jpnlFondoVerdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlFondoVerdeLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jblTitulo)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpnlFondoVerde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxtPago, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtTotalVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnPagarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jpnlFondoVerde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtxtTotalVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtxtPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtxtCambio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(62, 62, 62))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)))
                        .addComponent(jLabel3)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCancelarVenta)
                    .addComponent(btnPagarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void btnCancelarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarVentaActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnCancelarVentaActionPerformed

    private void btnPagarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarVentaActionPerformed
        if (this.validarPago()) {
            pagarTicket();
            setVisible(false);
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Favor de ingresar el efectivo que pago el cliente", "Mensaje del Sistema", JOptionPane.WARNING_MESSAGE);
            this.jtxtPago.setFocusable(true);
            this.jtxtPago.requestFocus();
            this.jtxtPago.selectAll();
        }
    }//GEN-LAST:event_btnPagarVentaActionPerformed

    private boolean validarPago() {
        try {
            BigDecimal pagado = new BigDecimal(this.jtxtPago.getText());
            BigDecimal total_pagar = new BigDecimal(this.jtxtPago.getText());
            return !this.jtxtPago.getText().isEmpty()//el campo de pago no sea acio
                    && pagado.compareTo(BigDecimal.ZERO) > 0//pago es mayor a cero
                    && pagado.compareTo(total_pagar) >= 0;//pago mas o igual al total a pagar
        } catch (Exception e) {
        }
        return false;
    }

    private void pagarTicket() {
        Ticket ticket = this.getTicketListoPagar();
        try {
            this.ticketController.actualizarTckt(ticket);
        } catch (Exception e) {
            log.error("Error al tratar de pagar ticket", e);
        }
    }

    private Ticket getTicketListoPagar() {
        Ticket ticket = this.getTicket_pagar();
        ticket.setCambio(new BigDecimal(this.jtxtCambio.getText()));
        ticket.setPago(new BigDecimal(this.jtxtPago.getText()));
        ticket.setPagado(true);
        return ticket;
    }

    private void jtxtPagoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtPagoKeyReleased
        if (!this.jtxtPago.getText().isEmpty()) {
            this.calcularCambio();
        }
    }//GEN-LAST:event_jtxtPagoKeyReleased

    private void jtxtPagoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtPagoFocusGained
        this.jtxtPago.selectAll();
    }//GEN-LAST:event_jtxtPagoFocusGained

    private void calcularCambio() {
        this.jtxtCambio.setText("--");
        BigDecimal pago_ingresado = BigDecimal.ZERO;
        BigDecimal cambio = BigDecimal.ZERO;
        BigDecimal total_pagar = new BigDecimal(this.jtxtTotalVenta.getText());
        try {
            pago_ingresado = new BigDecimal(this.jtxtPago.getText());
        } catch (Exception e) {
        }
        if (pago_ingresado.compareTo(BigDecimal.ZERO) > 0) {
            cambio = pago_ingresado.subtract(total_pagar).setScale(2, RoundingMode.HALF_UP);
            if (cambio.compareTo(BigDecimal.ZERO) > 0) {
                this.jtxtCambio.setText(cambio.toString());
            } else if (cambio.compareTo(BigDecimal.ZERO) == 0) {
                this.jtxtCambio.setText(BigDecimal.ZERO.toString());
            }
        }
    }

    public void setDatos(Ticket ticket_activo) {
        this.setTicket_pagar(ticket_activo);
        this.jtxtTotalVenta.setText(ticket_activo.getTotal().toString());
    }

    @Override
    public void setVisible(boolean b) {
        this.jtxtPago.setText("0.00");
        this.jtxtPago.setFocusable(true);
        this.jtxtPago.requestFocus();
        this.jtxtPago.selectAll();
        super.setVisible(b); //To change body of generated methods, choose Tools | Templates.
        this.setTicket_pagar(null);
    }

    public final void setMnemonic() {
        btnCancelarVenta.setMnemonic(KeyEvent.VK_ESCAPE);
        btnPagarVenta.setMnemonic(KeyEvent.VK_ENTER);

        getActionMap(btnCancelarVenta, "cerrar", KeyEvent.VK_ESCAPE);
        getActionMap(btnPagarVenta, "aceptar", KeyEvent.VK_ENTER);

    }

    public void getActionMap(JComponent componente, String nombreAccion, int tecla) {
        componente.getInputMap(JButton.WHEN_IN_FOCUSED_WINDOW).put(
                KeyStroke.getKeyStroke(tecla, 0), nombreAccion);
        componente.getActionMap().put(nombreAccion,
                newAbstractAction(nombreAccion));
    }

    public AbstractAction newAbstractAction(String nombreAccion) {
        if (nombreAccion.equals("cerrar")) {
            return new AbstractAction(nombreAccion) {
                @Override
                public void actionPerformed(ActionEvent evt) {
                    if (btnCancelarVenta.isEnabled()) {
                        btnCancelarVentaActionPerformed(evt);
                    }
                }
            };
        } else if (nombreAccion.equals("aceptar")) {
            return new AbstractAction(nombreAccion) {
                @Override
                public void actionPerformed(ActionEvent evt) {
                    if (btnPagarVenta.isEnabled()) {
                        btnPagarVentaActionPerformed(evt);
                    }
                }
            };
        }
        return null;
    }

    public Ticket getTicket_pagar() {
        return ticket_pagar;
    }

    public void setTicket_pagar(Ticket ticket_pagar) {
        this.ticket_pagar = ticket_pagar;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarVenta;
    private javax.swing.JButton btnPagarVenta;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jblTitulo;
    private javax.swing.JPanel jpnlFondoVerde;
    private javax.swing.JTextField jtxtCambio;
    private javax.swing.JTextField jtxtPago;
    private javax.swing.JTextField jtxtTotalVenta;
    // End of variables declaration//GEN-END:variables
}
