/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pos.stalupita.view;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import javax.annotation.Resource;
import javax.swing.AbstractAction;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import pos.stalupita.controller.ProductoController;
import pos.stalupita.herramientas.AdapterNumericoFormatMak;
import pos.stalupita.herramientas.RoundedBorderBtn;
import pos.stalupita.herramientas.Utilities;
import pos.stalupita.model.Categoria;
import pos.stalupita.model.Producto;
import pos.stalupita.model.UnidadMedida;

/**
 *
 * @author adrian.ake
 */
@Component(value = "prototype")
public class DlgRegistrar_prod extends javax.swing.JDialog {

    @Resource
    private ProductoController productoController;

    private Producto producto_edition = null;

    /**
     * Creates new form JdlgRegistrar_prod
     */
    public DlgRegistrar_prod(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Utilities.setDialogIcon(this);
        this.jtxtCosto.addKeyListener(new AdapterNumericoFormatMak(this.jtxtCosto, 8, 2));
        this.jtxtPrecioVenta.addKeyListener(new AdapterNumericoFormatMak(this.jtxtPrecioVenta, 8, 2));
        this.setMnemonic();
        this.cargarComponents();
    }

    @Autowired
    public DlgRegistrar_prod(ProductoController productoController) {
        super(null, ModalityType.APPLICATION_MODAL);
        initComponents();
        Utilities.setDialogIcon(this);
        this.productoController = productoController;
        this.jtxtCosto.addKeyListener(new AdapterNumericoFormatMak(this.jtxtCosto, 8, 2));
        this.jtxtPrecioVenta.addKeyListener(new AdapterNumericoFormatMak(this.jtxtPrecioVenta, 8, 2));
        this.setMnemonic();
        this.cargarComponents();
    }

    private void cargarComponents() {
        this.btnGuardar.setBorder(new RoundedBorderBtn(8));
        this.btnCancelar.setBorder(new RoundedBorderBtn(8));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jblTitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jtxtDescripcion = new javax.swing.JTextField();
        jtxtPrecioVenta = new javax.swing.JTextField();
        jtxtCosto = new javax.swing.JTextField();
        jcboxUme = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jcboxCategoria = new javax.swing.JComboBox();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jblTitulo.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jblTitulo.setForeground(new java.awt.Color(0, 51, 153));
        jblTitulo.setText("Registrar Producto");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(73, 80, 87));
        jLabel2.setText("Descripcion:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(73, 80, 87));
        jLabel3.setText("Costo(Compra) $ :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(73, 80, 87));
        jLabel4.setText("Precio(Venta) $ :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(73, 80, 87));
        jLabel5.setText("Unidad de Medida:");

        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/stalupita/view/resources/010_x-32.png"))); // NOI18N
        btnCancelar.setText("<html><center><b>Cancelar</b> &nbsp<font color = blue>(ESC)</font> </center></html>");
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/stalupita/view/resources/save-32.png"))); // NOI18N
        btnGuardar.setText("<html><center><b>Guardar</b> &nbsp<font color = blue>(Alt + G)</font> </center></html>");
        btnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jtxtDescripcion.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jtxtDescripcion.setForeground(new java.awt.Color(33, 37, 41));
        jtxtDescripcion.setText("Descripcion Producto");
        jtxtDescripcion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtDescripcionFocusGained(evt);
            }
        });

        jtxtPrecioVenta.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jtxtPrecioVenta.setForeground(new java.awt.Color(33, 37, 41));
        jtxtPrecioVenta.setText("0.00");
        jtxtPrecioVenta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtPrecioVentaFocusGained(evt);
            }
        });

        jtxtCosto.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jtxtCosto.setForeground(new java.awt.Color(33, 37, 41));
        jtxtCosto.setText("0.00");
        jtxtCosto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtCostoFocusGained(evt);
            }
        });

        jcboxUme.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jcboxUme.setForeground(new java.awt.Color(33, 37, 41));
        jcboxUme.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(73, 80, 87));
        jLabel6.setText("Categoria:");

        jcboxCategoria.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jcboxCategoria.setForeground(new java.awt.Color(33, 37, 41));
        jcboxCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(158, 158, 158))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcboxUme, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcboxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtCosto)
                            .addComponent(jtxtPrecioVenta))
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jblTitulo)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jtxtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jcboxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jcboxUme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxtPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void jtxtCostoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtCostoFocusGained
        this.jtxtCosto.selectAll();
    }//GEN-LAST:event_jtxtCostoFocusGained

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (this.validarCampos()) {
            this.guardarProducto();
            JOptionPane.showMessageDialog(null, "El producto ha sido guardado", "Mensaje del Sistema", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios", "Mensaje del Sistema", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void jtxtPrecioVentaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtPrecioVentaFocusGained
        this.jtxtPrecioVenta.selectAll();
    }//GEN-LAST:event_jtxtPrecioVentaFocusGained

    private void jtxtDescripcionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtDescripcionFocusGained
       this.jtxtDescripcion.selectAll();
    }//GEN-LAST:event_jtxtDescripcionFocusGained

    private void guardarProducto() {
        if (this.getProducto_edition() != null) {//es modificacion
            this.productoController.guardarUpdProducto(this.getProductoGenerado());
        } else {
            this.productoController.guardarProducto(this.getProductoGenerado());
        }
    }

    public void setTitulo(String titulo) {
        this.jblTitulo.setText(titulo);
    }

    private Producto getProductoGenerado() {
        Producto producto = new Producto();
        producto.setUnidadMedida((UnidadMedida) this.jcboxUme.getSelectedItem());
        producto.setCategoria((Categoria) this.jcboxCategoria.getSelectedItem());
        producto.setDescripcion(this.jtxtDescripcion.getText());
        producto.setCosto(new BigDecimal(this.jtxtCosto.getText()));
        producto.setPrecio(new BigDecimal(this.jtxtPrecioVenta.getText()));
        producto.setEstado(true);

        if (this.getProducto_edition() != null) {//es modificacion
            producto.setIdproducto(this.getProducto_edition().getIdproducto());
            producto.setCreatedAt(this.getProducto_edition().getCreatedAt());
            producto.setUpdatedAt(new Date());
        } else {//es nuevo producto
            producto.setIdproducto(0);//auto_increment           
            producto.setCreatedAt(new Date());
        }
        return producto;
    }

    private boolean validarCampos() {
        return !this.jtxtDescripcion.getText().isEmpty()
                && !this.jtxtCosto.getText().isEmpty()
                && !this.jtxtPrecioVenta.getText().isEmpty();
    }

    @Override
    public void setVisible(boolean b) {
        this.jtxtDescripcion.selectAll();
        this.jtxtDescripcion.setFocusable(true);
        super.setVisible(b); //To change body of generated methods, choose Tools | Templates.
    }

    public void resetDatos() {
        this.jtxtDescripcion.setText("Descripcion Producto");
        this.jtxtCosto.setText("0.00");
        this.jtxtPrecioVenta.setText("0.00");
        cargarCombos();
    }

    public void setEditProducto(Producto producto) {
        this.jtxtDescripcion.setText(producto.getDescripcion());
        this.jtxtCosto.setText(producto.getCosto().toString());
        this.jtxtPrecioVenta.setText(producto.getPrecio().toString());
        this.jcboxCategoria.setSelectedItem(producto.getCategoria());
        this.jcboxUme.setSelectedItem(producto.getUnidadMedida());
    }

    private void cargarCombos() {
        List<Categoria> categorias = this.productoController.getAllCategorias();
        this.jcboxCategoria.removeAllItems();
        for (Categoria categoria : categorias) {
            this.jcboxCategoria.addItem(categoria);
        }

        List<UnidadMedida> unidadMedidas = this.productoController.getAllUmes();
        this.jcboxUme.removeAllItems();
        for (UnidadMedida unidadMedida : unidadMedidas) {
            this.jcboxUme.addItem(unidadMedida);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jblTitulo;
    private javax.swing.JComboBox jcboxCategoria;
    private javax.swing.JComboBox jcboxUme;
    private javax.swing.JTextField jtxtCosto;
    private javax.swing.JTextField jtxtDescripcion;
    private javax.swing.JTextField jtxtPrecioVenta;
    // End of variables declaration//GEN-END:variables

    public Producto getProducto_edition() {
        return producto_edition;
    }

    public void setProducto_edition(Producto producto_edition) {
        this.producto_edition = producto_edition;
    }

    public final void setMnemonic() {
        getActionMap(btnGuardar, "guardar", KeyEvent.VK_G);
        getActionMap(btnCancelar, "cerrar", KeyEvent.VK_ESCAPE);
        btnGuardar.setMnemonic(KeyEvent.VK_G);
    }

    public void getActionMap(JComponent componente, String nombreAccion, int tecla) {
        componente.getInputMap(JButton.WHEN_IN_FOCUSED_WINDOW).put(
                KeyStroke.getKeyStroke(tecla, 0), nombreAccion);
        componente.getActionMap().put(nombreAccion,
                newAbstractAction(nombreAccion));
    }

    public AbstractAction newAbstractAction(String nombreAccion) {
        if (nombreAccion.equals("cerrar")) {
            return new AbstractAction(nombreAccion) {
                @Override
                public void actionPerformed(ActionEvent evt) {
                    if (btnCancelar.isEnabled()) {
                        btnCancelarActionPerformed(evt);
                    }
                }
            };
        } else if (nombreAccion.equals("guardar")) {
            return new AbstractAction(nombreAccion) {
                @Override
                public void actionPerformed(ActionEvent evt) {
                    if (btnGuardar.isEnabled()) {
                        btnGuardarActionPerformed(evt);
                    }
                }
            };
        }
        return null;
    }
}
