/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pos.stalupita.view;

import javax.annotation.Resource;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import pos.stalupita.herramientas.Utilities;

/**
 *
 * @author adrian.ake
 */
@Component
public class FrmMain extends javax.swing.JFrame {

    @Resource
    private DlgPrincipal jdlgPrincipal;

    /**
     * Creates new form jFrmMain
     */
    public FrmMain() {
        initComponents();
        Utilities.setFrameIcon(this);
        cargarTam();
    }

    @Autowired
    public FrmMain(DlgPrincipal jdlgPrincipal) {
        initComponents();
        Utilities.setFrameIcon(this);
        this.jdlgPrincipal = jdlgPrincipal;
        cargarTam();
    }

    private void cargarTam() {
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    public ImageIcon getImageIcon() {
        return Utilities.getImageIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(149, 163, 190));
        setIconImage(getIconImage());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
